100.what-is-oceanbase-connector-j=什么是 OceanBase Connector J
200.install-connection=安装与连接
300.user-guide=使用指南
100.quick-start=快速入门
200.data-source-and-url=数据源和 URL
300.java-data-stream=Java 数据转换
300.lob-data-type=LOB 数据类型
400.statement-cache=Statement 缓存
700.result-set=结果集
900.failover-and-load-balancing=Failover 和 Load-Balancing
400.reference-information=参考信息
100.features-specific-to-oracle-mode=Oracle 模式特有功能
100.binary-protocol=二进制协议（Prepared Statements）
500.distributed-transactions=分布式事务
300.common-interfaces=常用接口
500.version-release-records=版本发布记录
9800.V2.4=V2.4
9900.V2.2=V2.2
