1.what-is-oceanbase-connector-j=What is OceanBase Connector J?
2.install-connection=Install Driver
3.user-guide=Instructions
1.quick-start=Quick start
2.data-source-and-url=Data sources and URL
3.java-data-stream=Java data streams
3.lob-data-type=Use LOBs
4.statement-cache=Statement caching
7.result-set=Result set
9.failover-and-load-balancing=Failover and Load-Balancing
4.reference-information=Reference
1.features-specific-to-oracle-mode=Features specific to the Oracle mode
1.binary-protocol=Binary Protocol (Prepared Statements)
5.distributed-transactions=Distributed transactions
3.common-interfaces=Common APIs
5.version-release-records=版本发布记录
98.V2.4=V2.4
99.V2.2=V2.2