1.what-is-oceanbase-connector-j=什么是 OceanBase Connector J
2.user-guide=使用指南
2.basic-operations=基本操作
4.java-data-stream=Java 数据流
5.use-lob=使用 LOB
7.data-source-and-url=数据源和 URL
8.result-set=结果集
9.statement-cache=Statement 缓存
14.common-interfaces=常用接口
15.reference-information=参考信息
3.features-specific-to-oracle-mode=Oracle 模式特有功能
5.distributed-transactions=分布式事务