2.what-is-oceanbase-connector-j=什么是 OceanBase Connector J
3.user-guide=使用指南
3.basic-operations=基本操作
6.java-data-stream=Java 数据流
7.use-lob=使用 LOB
8.data-source-and-url=数据源和 URL
9.result-set=结果集
10.statement-cache=Statement 缓存
16.common-interfaces=常用接口
17.reference-information=参考信息
4.features-specific-to-oracle-mode=Oracle 模式特有功能
1.binary-protocol=二进制协议（Prepared Statements）
5.distributed-transactions=分布式事务